sudo: required
language: generic
services:
  - docker

before_install: 
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh 
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

deploy: 
  provider: script 
  script: 
    heroku container:push web --app monitor-prodd;
    heroku container:release web --app monitor-prodd;
  on: 
    branch: devops
